CREATE DATABASE clinica_medica;

use clinica_medica;
		
CREATE TABLE MEDICO(
 CRM INT PRIMARY KEY,
 NOME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(20) NOT NULL,
 TELEFONE INT UNIQUE,
 DATA_NASC DATE,
 ESPECIALIZACAO VARCHAR(25) 
 CHECK (ESPECIALIZACAO IN ('CARDIOLOGISTA', 'NUTRICIONISTA'))
);

CREATE TABLE PACIENTE(
    ID int primary key,
    CPF int unique,
    Nome varchar(100),
    Endereco varchar (75),
    Telefone int unique,
    Tipo_Exame varchar(25) 
    check (Tipo_Exame in ('laboratorial', 'clinico'))
);

CREATE TABLE CONSULTA (
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID), 
    DATA_CONSULT DATE NOT NULL,
    VALOR DOUBLE NOT NULL,
    TIPO_PAG VARCHAR(20) UNIQUE
);

CREATE TABLE EXAME (
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID), 
    DATA_EXAME DATE,
    HORARIO TIME,
    VALOR DOUBLE NOT NULL,
    TIPO_PAG VARCHAR(20) UNIQUE,	
    TIPO_EXAME VARCHAR(50) UNIQUE
);

alter table medico
modify telefone varchar(30);

alter table paciente
modify telefone varchar(30);

insert into MEDICO (CRM, NOME, EMAIL, TELEFONE, DATA_NASC, ESPECIALIZACAO) 
values ( 1, "A", "A@email.com","00912345678", '1998-12-25', "Cardiologista");

INSERT INTO MEDICO (CRM, NOME, EMAIL, TELEFONE, DATA_NASC, ESPECIALIZACAO) VALUES
(2, 'B', 'B@email.com', '05999887766', '1940-06-27', 'NUTRICIONISTA'),
(3, 'C', 'C@email.com', '03999112233', '1986-01-30', 'NUTRICIONISTA');

INSERT INTO PACIENTE (ID, CPF, Nome, Endereco, Telefone, Tipo_Exame) values
(1, 00000000012, 'Um', 'Rua A, 3', '01234567890', 'Laboratorial'),
(2, 00000000123, 'Dois', 'Rua B, 7', '12345678900', 'Clinico'),
(3, 00000001234, 'Três', 'Rua C, 12', '23456789012', 'Laboratorial'),
(4, 00000012345, 'Quatro', 'Rua D, 18', '34567890123', 'Imagem'),
(5, 00000123456, 'Cinco', 'Rua E, 25', '45678901234', 'Clinico');

alter table paciente
drop check paciente_chk_1;

INSERT INTO consulta (ID_MEDICO, ID_PACIENTE, DATA_CONSULT, VALOR, TIPO_PAG) VALUES
(2, 4, '2025-12-19', '500.00', 'Dinheiro'),
(1, 5, '2003-06-30', '1600.00', 'Crédito'),
(3, 2,'2012-03-26', '300.00', 'Débito'),
(1, 1, '2025-01-03', '3700.00', 'pix');

DELETE FROM PACIENTE
WHERE ID = 3;

UPDATE PACIENTE SET TELEFONE = '99999999999' WHERE ID = 2;

SELECT * FROM PACIENTE;

SELECT NOME, ESPECIALIZACAO FROM MEDICO;

SELECT * FROM CONSULTA WHERE ID_MEDICO = 2;

SELECT * FROM MEDICO WHERE ESPECIALIZACAO = "CARDIOLOGISTA";

SELECT COUNT(*) AS TOTAL_PACIENTES FROM PACIENTE;

SELECT MIN(DATA_CONSULT) AS MAIS_ANTIGA FROM CONSULTA;

SELECT AVG(VALOR) AS PRECO_MEDIO FROM CONSULTA WHERE VALOR;

SELECT NOME FROM PACIENTE ORDER BY nome ASC;

SELECT ID_MEDICO, COUNT(*) AS Quantidade FROM consulta GROUP BY ID_MEDICO;,

SELECT PACIENTE.Nome AS Nome_Paciente, CONSULTA.DATA_CONSULT
FROM PACIENTE
JOIN CONSULTA ON PACIENTE.ID = CONSULTA.ID_PACIENTE;

SELECT MEDICO.NOME AS Nome_Medico, MEDICO.ESPECIALIZACAO, PACIENTE.Nome AS Nome_Paciente
FROM MEDICO
JOIN CONSULTA ON MEDICO.CRM = CONSULTA.ID_MEDICO
JOIN PACIENTE ON CONSULTA.ID_PACIENTE = PACIENTE.ID;

SELECT MEDICO.NOME AS Nome_Medico, MEDICO.ESPECIALIZACAO, PACIENTE.Nome AS Nome_Paciente
FROM MEDICO
JOIN CONSULTA ON MEDICO.CRM = CONSULTA.ID_MEDICO
JOIN PACIENTE ON CONSULTA.ID_PACIENTE = PACIENTE.ID;

